# Generated by Django 5.2.4 on 2025-08-05 17:29

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='due_date',
        ),
        migrations.AddField(
            model_name='reminder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 8, 5, 17, 29, 27, 608380, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminder',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
