# Generated by Django 5.2.4 on 2025-08-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_reminder_due_date_reminder_date_reminder_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
