# Generated by Django 5.2.5 on 2025-08-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_reminder_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
