# Generated by Django 5.2.5 on 2025-08-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_reminder_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat',
            field=models.CharField(choices=[('none', 'No Repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
    ]
